on:
  push: 
    tags:
      - '*'

name: release

jobs:
  build:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: build code
        uses: actions/checkout@v2
      - name: build project
        run: |
          npm ci
          npm test
          npm run lint
          npm run build
          zip -r artifact lib src package.json index.html LICENSE README.md
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifact.zip
          asset_name: artifact.zip
          tag: ${{ github.ref }}
          overwrite: true
